spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    properties:
      hibernate.hbm2ddl.auto: create-drop
#      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
